[package]
name = "sports_cards"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
winapi = "0.2.8"
kernel32-sys = "0.2.1"